DoctorFAM.Presentation/Areas/Admin/Controllers/HealthHouseController.cs
using DoctorFAM.Application.Extensions;
using DoctorFAM.Application.Services.Implementation;
using DoctorFAM.Application.Services.Interfaces;
using DoctorFAM.Domain.ViewModels.Admin.HealthHouse;
using DoctorFAM.Domain.ViewModels.Admin.HealthHouse.DeathCertificate;
using DoctorFAM.Domain.ViewModels.Admin.HealthHouse.HomeLabratory;
using DoctorFAM.Domain.ViewModels.Admin.HealthHouse.HomeNurse;
using DoctorFAM.Domain.ViewModels.Admin.HealthHouse.HomePatientTransport;
using DoctorFAM.Domain.ViewModels.Admin.HealthHouse.HomePharmacy;
using Microsoft.AspNetCore.Mvc;

namespace DoctorFAM.Web.Areas.Admin.Controllers
{
    public class HealthHouseController : AdminBaseController
    {
        #region Ctor

        private readonly IHomeVisitService _homeVisit;
        private readonly IHomeNurseService _homeNurse;
        private readonly IDeathCertificateService _deathCertificate;
        private readonly IHomePatientTransportService _homePatientTransportService;
        private readonly IHomePharmacyServicec _homePharmacyService;
        private readonly IHomeLaboratoryServices _homeLaboratoryServices;
        private readonly IPharmacyService _pharmacyService;
        private readonly IRequestService _requestService;
        private readonly INurseService _nurseService;
        private readonly ILaboratoryService _laboratoryService;

        public HealthHouseController(IHomeVisitService homeVisit, IHomeNurseService homeNurse,
                        IDeathCertificateService deathCertificate, IHomePatientTransportService homePatientTransportService
                        , IHomePharmacyServicec homePharmacyService, IHomeLaboratoryServices homeLaboratoryServices, IPharmacyService pharmacyService
                              , IRequestService requestService, INurseService nurseService, ILaboratoryService laboratoryService)
        {
            _homeVisit = homeVisit;
            _homeNurse = homeNurse;
            _deathCertificate = deathCertificate;
            _homePatientTransportService = homePatientTransportService;
            _homePharmacyService = homePharmacyService;
            _homeLaboratoryServices = homeLaboratoryServices;
            _pharmacyService = pharmacyService;
            _requestService = requestService;
            _nurseService = nurseService;
            _laboratoryService = laboratoryService;
        }

        #endregion

        #region Home Visit

        #region Listt Of Home Visit

        public async Task<IActionResult> ListOfHomeVisits(FilterHomeVisistViewModel filter)
        {
            return View(await _homeVisit.FilterHomeVisit(filter));
        }

        #endregion

        #region Home Visit Detail 

        public async Task<IActionResult> HomeVisitRequestDetail(ulong requestId)
        {
            #region Get Request

            var model = await _homeVisit.ShowHomeVisitDetail(requestId);

            if (model == null) return NotFound();

            #endregion

            return View(model);
        }

        #endregion

        #endregion

        #region Home Nurse 

        #region List Of Home Nurse 

        public async Task<IActionResult> ListOfHomeNurse(FilterHomeNurseViewModel filter)
        {
            return View(await _homeNurse.FilterHomeNurse(filter));
        }

        #endregion

        #region Home Nurse Detail

        public async Task<IActionResult> HomeNurseRequestDetail(ulong requestId)
        {
            #region Get Request Detail

            var model = await _nurseService.FillHomeNurseRequestAdminPanelViewModel(requestId);
            if (model == null) return NotFound();

            #endregion

            return View(model);
        }

        #endregion

        #endregion

        #region Death Certificate

        #region List Of Death Certificate

        public async Task<IActionResult> ListOfDeathCertificate(FilterDeathCertificateViewModel filter)
        {
            return View(await _deathCertificate.FilterDeathCertificate(filter));
        }

        #endregion

        #region Death Certificate Detail

        public async Task<IActionResult> DeathCertificateRequestDetail(ulong requestId)
        {
            #region Get Request

            var model = await _deathCertificate.ShowDeathCertificateDetail(requestId);

            if (model == null) return NotFound();

            #endregion

            return View(model);
        }

        #endregion

        #endregion

        #region Home Patient Transport

        #region List Of Home Patient Transport

        public async Task<IActionResult> ListOfHomePatientTransport(FilterHomePatientTransportViewModel filter)
        {
            return View(await _homePatientTransportService.FilterHomePatientTransport(filter));
        }

        #endregion

        #region Home Patient Transport Detail

        public async Task<IActionResult> HomePatientTransportRequestDetail(ulong requestId)
        {
            #region Get Request

            var model = await _homePatientTransportService.ShowHomePatientTransportDetail(requestId);

            if (model == null) return NotFound();

            #endregion

            return View(model);
        }

        #endregion

        #endregion

        #region Home Pharmacy 

        #region List Of Home Pharmacy

        public async Task<IActionResult> ListOfHomePharmacy(FilterHomePharmacyViewModel filter)
        {
            return View(await _homePharmacyService.FilterHomePharmacy(filter));
        }

        #endregion

        #region Home Pharmacy Detail

        public async Task<IActionResult> HomePharmacyRequestDetail(ulong requestId)
        {
            #region Get Pharmacy Request Detail

            var model = await _pharmacyService.FillHomePharmacyRequestAdminPanelViewModel(requestId);
            if (model == null) return NotFound();

            #endregion

            return View(model);
        }

        #endregion

        #region Invoice Finalization And See Invoice Detail

        public async Task<IActionResult> InvoiceFinalization(ulong requestId)
        {
            #region Get Request By Id 

            var request = await _requestService.GetRequestById(requestId);
            if (request == null) return NotFound();

            #endregion

            #region Fill Page Model

            var model = await _pharmacyService.FinallyInvoiceFromAdminViewModel(requestId);
            if (model == null)
            {
                return NotFound();
            }

            #endregion

            #region Send View Bags

            ViewBag.RequestId = requestId;
            ViewBag.TotalPrice = await _pharmacyService.GetSumOfInvoiceHomePharmacyRequestDetailPricing(requestId, request.OperationId.Value);
            var TransferingPrice = await _requestService.GetRequestTransferingPriceFromOperator(request.OperationId.Value, requestId);
            if (TransferingPrice != null)
            {
                ViewBag.TransferingPrice = TransferingPrice.Price;
            }

            #endregion

            return View(model);
        }

        #endregion

        #endregion

        #region Home Labratory

        #region List Of Home Labratory

        public async Task<IActionResult> ListOfHomeLabratory(FilterHomeLabratoryViewModel filter)
        {
            return View(await _homeLaboratoryServices.FilterHomeLabratory(filter));
        }

        #endregion

        #region Home Pharmacy Detail

        public async Task<IActionResult> HomeLabratoryRequestDetail(ulong requestId)
        {
            #region Get Request

            var model = await _laboratoryService.FillHomePharmacyRequestDetailAdminSide(requestId, User.GetUserId());
            if (model == null) return NotFound();
            if (model == null) return NotFound();
            if (model.User == null) return NotFound();
            if (model.Request == null) return NotFound();
            if (model.HomeLaboratoryRequestDetail == null) return NotFound();
            if (model.PatientRequestDetail == null) return NotFound();
            if (model.PatientRequestDateTimeDetail == null) return NotFound();
            if (model.Patient == null) return NotFound();

            #endregion

            return View(model);
        }

        #endregion

        #endregion
    }
}

DoctorFAM.Presentation/Areas/Supporter/Controllers/HealthHouseController.cs
using DoctorFAM.Application.Extensions;
using DoctorFAM.Application.Security;
using DoctorFAM.Application.Services.Implementation;
using DoctorFAM.Application.Services.Interfaces;
using DoctorFAM.Domain.ViewModels.Admin.HealthHouse;
using DoctorFAM.Domain.ViewModels.Admin.HealthHouse.DeathCertificate;
using DoctorFAM.Domain.ViewModels.Admin.HealthHouse.HomeLabratory;
using DoctorFAM.Domain.ViewModels.Admin.HealthHouse.HomeNurse;
using DoctorFAM.Domain.ViewModels.Admin.HealthHouse.HomePatientTransport;
using DoctorFAM.Domain.ViewModels.Admin.HealthHouse.HomePharmacy;
using Microsoft.AspNetCore.Mvc;

namespace DoctorFAM.Web.Areas.Supporter.Controllers
{
    [PermissionChecker("SupporterPanel")]
    public class HealthHouseController : SupporterBaseController
    {
        #region Ctor

        private readonly IHomeVisitService _homeVisit;
        private readonly IHomeNurseService _homeNurse;
        private readonly IDeathCertificateService _deathCertificate;
        private readonly IHomePatientTransportService _homePatientTransportService;
        private readonly IHomePharmacyServicec _homePharmacyService;
        private readonly IHomeLaboratoryServices _homeLaboratoryServices;
        private readonly IPharmacyService _pharmacyService;
        private readonly INurseService _nurserService;
        private readonly ILaboratoryService _laboratoryService;

        public HealthHouseController(IHomeVisitService homeVisit, IHomeNurseService homeNurse, IDeathCertificateService deathCertificate, IHomePatientTransportService homePatientTransportService,
                                        IHomePharmacyServicec homePharmacyService, IHomeLaboratoryServices homeLaboratoryServices, 
                                                IPharmacyService pharmacyService, INurseService nurserService , ILaboratoryService loboratoryService)
        {
            _homeVisit = homeVisit;
            _homeNurse = homeNurse;
            _deathCertificate = deathCertificate;
            _homePatientTransportService = homePatientTransportService;
            _homePharmacyService = homePharmacyService;
            _homeLaboratoryServices = homeLaboratoryServices;
            _pharmacyService = pharmacyService;
            _nurserService = nurserService;
            _laboratoryService = loboratoryService;
        }

        #endregion

        #region Home Visit

        #region Listt Of Home Visit

        [PermissionChecker("HomeVisit")]
        public async Task<IActionResult> ListOfHomeVisits(FilterHomeVisistViewModel filter)
        {
            return View(await _homeVisit.FilterHomeVisit(filter));
        }

        #endregion

        #region Home Visit Detail 

        [PermissionChecker("HomeVisit")]
        public async Task<IActionResult> HomeVisitRequestDetail(ulong requestId)
        {
            #region Get Request

            var model = await _homeVisit.ShowHomeVisitDetail(requestId);

            if (model == null) return NotFound();

            #endregion

            return View(model);
        }

        #endregion

        #endregion

        #region Home Nurse 

        #region List Of Home Nurse 

        [PermissionChecker("HomeNurse")]
        public async Task<IActionResult> ListOfHomeNurse(FilterHomeNurseViewModel filter)
        {
            return View(await _homeNurse.FilterHomeNurse(filter));
        }

        #endregion

        #region Home Nurse Detail

        [PermissionChecker("HomeNurse")]
        public async Task<IActionResult> HomeNurseRequestDetail(ulong requestId)
        {
            #region Get Request Detail

            var model = await _nurserService.FillHomeNurseRequestAdminPanelViewModel(requestId);
            if (model == null) return NotFound();

            #endregion

            return View(model);
        }

        #endregion

        #endregion

        #region Death Certificate

        #region List Of Death Certificate

        [PermissionChecker("DeathCertificate")]
        public async Task<IActionResult> ListOfDeathCertificate(FilterDeathCertificateViewModel filter)
        {
            return View(await _deathCertificate.FilterDeathCertificate(filter));
        }

        #endregion

        #region Death Certificate Detail

        [PermissionChecker("DeathCertificate")]
        public async Task<IActionResult> DeathCertificateRequestDetail(ulong requestId)
        {
            #region Get Request

            var model = await _deathCertificate.ShowDeathCertificateDetail(requestId);

            if (model == null) return NotFound();

            #endregion

            return View(model);
        }

        #endregion

        #endregion

        #region Home Patient Transport

        #region List Of Home Patient Transport

        [PermissionChecker("PetientTransport")]
        public async Task<IActionResult> ListOfHomePatientTransport(FilterHomePatientTransportViewModel filter)
        {
            return View(await _homePatientTransportService.FilterHomePatientTransport(filter));
        }

        #endregion

        #region Home Patient Transport Detail

        [PermissionChecker("PetientTransport")]
        public async Task<IActionResult> HomePatientTransportRequestDetail(ulong requestId)
        {
            #region Get Request

            var model = await _homePatientTransportService.ShowHomePatientTransportDetail(requestId);

            if (model == null) return NotFound();

            #endregion

            return View(model);
        }

        #endregion

        #endregion

        #region Home Pharmacy 

        #region List Of Home Pharmacy

        [PermissionChecker("HomePharmacy")]
        public async Task<IActionResult> ListOfHomePharmacy(FilterHomePharmacyViewModel filter)
        {
            return View(await _homePharmacyService.FilterHomePharmacy(filter));
        }

        #endregion

        #region Home Pharmacy Detail

        [PermissionChecker("HomePharmacy")]
        public async Task<IActionResult> HomePharmacyRequestDetail(ulong requestId)
        {
            #region Get Pharmacy Request Detail

            var model = await _pharmacyService.FillHomePharmacyRequestAdminPanelViewModel(requestId);
            if (model == null) return NotFound();

            #endregion

            return View(model);
        }

        #endregion

        #endregion

        #region Home Labratory

        #region List Of Home Labratory

        [PermissionChecker("HomeLaboratory")]
        public async Task<IActionResult> ListOfHomeLabratory(FilterHomeLabratoryViewModel filter)
        {
            return View(await _homeLaboratoryServices.FilterHomeLabratory(filter));
        }

        #endregion

        #region Home Pharmacy Detail

        [PermissionChecker("HomeLaboratory")]
        public async Task<IActionResult> HomeLabratoryRequestDetail(ulong requestId)
        {
            #region Get Request

            var model = await _laboratoryService.FillHomePharmacyRequestDetailAdminSide(requestId, User.GetUserId());
            if (model == null) return NotFound();
            if (model == null) return NotFound();
            if (model.User == null) return NotFound();
            if (model.Request == null) return NotFound();
            if (model.HomeLaboratoryRequestDetail == null) return NotFound();
            if (model.PatientRequestDetail == null) return NotFound();
            if (model.PatientRequestDateTimeDetail == null) return NotFound();
            if (model.Patient == null) return NotFound();

            #endregion

            return View(model);
        }

        #endregion

        #endregion
    }
}

DoctorFAM.Presentation/Areas/Admin/Views/HealthHouse/ListOfDeathCertificate.cshtml
@model DoctorFAM.Domain.ViewModels.Admin.HealthHouse.DeathCertificate.FilterDeathCertificateViewModel
@using DoctorFAM.Domain.ViewModels.Admin.HealthHouse
@using DoctorFAM.Application.Extensions
@using DoctorFAM.Application.Convertors
@using DoctorFAM.Domain.ViewModels.Common
@using DoctorFAM.Domain.Enums.Request
@inject IViewLocalizer Localizer
@inject IHtmlLocalizer<SharedLocalizer> SharedHtmlLocalizer


@{
    ViewData["Title"] = @Localizer["List Of Death Certificate Request"];
}

@section Styles
{

}

@section Scripts
{
<partial name="_JqueryValidation" />
}

@section Breadcrumb
{
<li>
    <a href="javascript:void(0)"> @ViewData["Title"] </a>
</li>
}

<div class="row">
    <div class="col-lg-3 col-sm-12">
        <div class="widget">
            <div class="widget-header bordered-bottom bordered-green">
                <span class="widget-caption"> @Localizer["Death Certificate"] </span>
            </div>
            <div class="widget-body">
                <div>
                    <form asp-action="ListOfDeathCertificate" asp-controller="HealthHouse" asp-area="Admin" id="filter-search" method="get">

                        <input type="hidden" asp-for="Page" />

                        <div class="form-group">
                            <label asp-for="Username"> @Localizer["Username"] </label>
                            <input type="text" class="form-control" asp-for="Username">
                        </div>

                        <div class="form-group">
                            <label asp-for="UserEmail"> @Localizer["Email"] </label>
                            <input type="text" class="form-control" asp-for="UserEmail">
                        </div>

                        <div class="form-group">
                            <label asp-for="UserMobile"> @Localizer["Mobile"] </label>
                            <input type="text" class="form-control" asp-for="UserMobile">
                        </div>

                        <div class="form-group">
                            <label asp-for="RequestState"> @Localizer["State"] </label>
                            <select asp-for="RequestState" class="form-control" asp-items="Html.GetEnumSelectList(typeof(RequestStateForFilterAdminSide))"></select>
                        </div>

                        <div class="form-group">
                            <label asp-for="FilterRequestAdminSideOrder"> @Localizer["Order By"] </label>
                            <select asp-for="FilterRequestAdminSideOrder" class="form-control" asp-items="Html.GetEnumSelectList(typeof(FilterRequestAdminSideOrder))"></select>
                        </div>

                        <hr />

                        <div class="row">
                            <div class="col-md-12 flex-style">
                                <button type="submit" class="btn btn-labeled w-100 btn-palegreen">
                                    <i class="btn-label glyphicon glyphicon-filter"></i>@Localizer["Filter"]
                                </button>

                                @if (Context.Request.QueryString.HasValue)
                                {
                                    <a asp-action="ListOfDeathCertificate" asp-controller="HealthHouse" asp-area="Admin" class="btn btn-labeled w-100 btn-darkorange mr-10px">
                                        <i class="btn-label glyphicon glyphicon-remove"></i>@Localizer["Delete Filter"]
                                    </a>
                                }
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-9 col-sm-12">
        <div class="well with-header with-footer table-responsive">
            <div class="header bordered-azure">
                <div class="flex-style">
                    <span>@ViewData["Title"]</span>
                    <span>@Model.GetShownEntitiesPagesTitle()</span>
                </div>
            </div>

            @if (Model.Entities != null && Model.Entities.Any())
            {
                <table class="table table-hover table-bordered tc vm">
                    <thead class="tc vm">
                        <tr class="tc vm">
                               <th class="tc vm">
                                @Localizer["User Avatar"]
                            </th>
                            <th class="tc vm">
                                @Localizer["User Email"]
                            </th>
                            <th class="tc vm">
                                @Localizer["Date Time"]
                            </th>
                            <th class="tc vm">
                                @Localizer["State"]
                            </th>
                            <th class="tc vm">
                                @Localizer["Options"]
                            </th>
                        </tr>
                    </thead>
                    <tbody class="tc vm">
                        @foreach (var request in Model.Entities)
                        {
                <tr class="tc vm">
                                <td class="vm">
                                    <div class="flex-style-center">
                                        <img src="@request.User.GetUserAvatar()" class="avatar-style" style="border-radius:50px;" />
                                        <div class="mr-10px">
                                            <span> @request.User.Username </span>
                                        </div>
                                    </div>
                                </td>
                                <td class="tc vm">
                                    <p>
                                        @Localizer["Email"] :
                                        @if (request.User.Email == null)
                                        {
                                            <span class="mr-8px label label-orange">@Localizer["Empty"] </span>
                                        }
                                        else
                                        {
                                            @request.User.Email
                                        }
                                    </p>
                                    @if (!string.IsNullOrEmpty(request.User.Mobile))
                                    {
                                        <hr class="margin-7" />
                                        <p>@Localizer["Mobile"] : @request.User.Mobile</p>
                                    }
                                </td>
                                <td class="tc vm">
                                    <p>  @request.CreateDate.ToStringShamsiDate() </p>
                                    <p> @request.CreateDate.Hour:@request.CreateDate.Minute:@request.CreateDate.Second</p>
                                </td>
                                <td class="tc vm">
                                    <p>

                                        @if (request.RequestState == DoctorFAM.Domain.Enums.Request.RequestState.Paid)
                                        {
                                            <span class="mr-8px label label-success"> @Localizer["Paid"] </span>
                                        }

                                        @if (request.RequestState == DoctorFAM.Domain.Enums.Request.RequestState.TramsferringToTheBankingPortal)
                                        {
                                            <span class="mr-8px label label-info"> @Localizer["Paying"] </span>
                                        }

                                        @if (request.RequestState == DoctorFAM.Domain.Enums.Request.RequestState.unpaid)
                                        {
                                            <span class="mr-8px label label-danger"> @Localizer["unpaid"]  </span>
                                        }

                                        @if (request.RequestState == DoctorFAM.Domain.Enums.Request.RequestState.WaitingForCompleteInformationFromUser)
                                        {
                                            <span class="mr-8px label label-danger"> @Localizer["Awaiting Payment"]   </span>
                                        }

                                        @if (request.RequestState == DoctorFAM.Domain.Enums.Request.RequestState.Finalized)
                                        {
                                            <span class="mr-8px label label-primary" style="  background-image: linear-gradient(#ff00cc, #333399) !important;"> @Localizer["Finalized"]   </span>
                                        }

                                    </p>
                                </td>
                               
                                <td class="tc vm">
                                    <a asp-action="DeathCertificateRequestDetail" asp-controller="HealthHouse" asp-area="Admin" asp-route-requestId="@request.Id" class="btn btn-azure btn-circle btn-xs"><i class="glyphicon glyphicon-eye-open"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

                <div class="footer tc">

                    <partial name="_AdminPaging" model="@Model.GetCurrentPaging()" />

                </div>
            }
            else
            {
                <partial name="_AdminNotFoundPartial" />
            }
        </div>
    </div>
</div>