DoctorFAM.Presentation/Controllers/FocalPointController.cs
#region Usings

using DoctorFAM.Application.Convertors;
using DoctorFAM.Application.Extensions;
using DoctorFAM.Application.Services.Interfaces;
using DoctorFAM.Domain.ViewModels.Site.Notification;
using DoctorFAM.Domain.ViewModels.Site.Reservation;
using DoctorFAM.Web.Hubs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using System.Text;
using DoctorFAM.Domain.DTOs.ZarinPal;
using DoctorFAM.Domain.Entities.Wallet;
using DoctorFAM.Application.StaticTools;
using DoctorFAM.Application.CQRS.SiteSide.FocalPoint.Queries.DoctorPage;
using DoctorFAM.Web.HttpManager;
using DoctorFAM.Application.CQRS.SiteSide.FocalPoint.Commands;
using DoctorFAM.Domain.ViewModels.Site.Story;

#endregion

namespace DoctorFAM.Web.Controllers;

public class FocalPointController : SiteBaseController
{
    #region Ctor

    private readonly IDoctorsService _doctorService;
    private readonly ISiteSettingService _siteSettingService;
    private readonly IReservationService _reservationService;
    private readonly IHomeVisitService _homeVisitService;
    private readonly IHubContext<NotificationHub> _notificationHub;
    private readonly INotificationService _notificationService;
    private readonly IUserService _userService;
    private readonly IWalletService _walletService;
    private readonly IWorkAddressService _workAddressService;

    public FocalPointController(IDoctorsService doctorsService,
                                ISiteSettingService siteSettingService,
                                IReservationService reservationService,
                                IHomeVisitService homeVisitService,
                                IHubContext<NotificationHub> notificationHub,
                                INotificationService notificationService,
                                IUserService userService,
                                IWalletService walletService,
                                IWorkAddressService workAddressService)
    {
        _doctorService = doctorsService;
        _siteSettingService = siteSettingService;
        _reservationService = reservationService;
        _homeVisitService = homeVisitService;
        _notificationHub = notificationHub;
        _notificationService = notificationService;
        _userService = userService;
        _walletService = walletService;
        _workAddressService = workAddressService;
    }

    #endregion

    #region Doctor Page 

    [HttpGet("DocPage/{userId}/{name}")]
    public async Task<IActionResult> DocPage(ulong userId, string name)
    {
        #region Fill Page Model 

        var model = await _doctorService.FillDoctorPageDetailInReservationPage(userId);
        if (model == null) return NotFound();

        #endregion

        return View(model);
    }

    #endregion

    #region New Doctor Page 

    [HttpGet("NewDocPage/{userId}/{name}")]
    public async Task<IActionResult> NewDocPage(ShowDoctorInfoQuery query, CancellationToken cancellation = default)
    {
        #region Fill Page Model 

        var model = await Mediator.Send(query, cancellation);
        if (model == null) return NotFound();

        #endregion

        if (User.Identity.IsAuthenticated)
        {
            if (model.User.Id == User.GetUserId())
            {
                return View("EditDoctorInfoByDoctor", model);
            }
        }

        return View(model);
    }

    #endregion

    #region Edit Doctor User Avatar

    [HttpPost]
    public async Task<IActionResult> EditUserAvatar(CancellationToken cancellationToken = default)
    {
        string result = string.Empty;
        var files = Request.Form.Files;

        List<EditProfilePictureCommand> command = new List<EditProfilePictureCommand>();

        foreach (var file in files)
        {
            EditProfilePictureCommand newInstance = new EditProfilePictureCommand()
            {
                Picture = file,
                UserId = User.GetUserId()
            };

            command.Add(newInstance);
        }

        bool res = await Mediator.Send(command.First(), cancellationToken);
        if (res)
        {
            return ApiResponse.SetResponse(ApiResponseStatus.Success, null, "عملیات با موفقیت انجام شده است.");
        }

        return ApiResponse.SetResponse(ApiResponseStatus.Danger, null, "عملیات باشکست مواجه شده است.");
    }

    #endregion

    #region Edit Doctor Banner Image

    [HttpPost]
    public async Task<IActionResult> EditDoctorBannerImage(CancellationToken cancellationToken = default)
    {
        string result = string.Empty;
        var files = Request.Form.Files;

        List<EditDoctorBannerImageCommand> command = new List<EditDoctorBannerImageCommand>();

        foreach (var file in files)
        {
            EditDoctorBannerImageCommand newInstance = new EditDoctorBannerImageCommand()
            {
                Picture = file,
                UserId = User.GetUserId()
            };

            command.Add(newInstance);
        }

        bool res = await Mediator.Send(command.First(), cancellationToken);
        if (res)
        {
            return ApiResponse.SetResponse(ApiResponseStatus.Success, null, "عملیات با موفقیت انجام شده است.");
        }

        return ApiResponse.SetResponse(ApiResponseStatus.Danger, null, "عملیات باشکست مواجه شده است.");
    }

    #endregion

    #region Doctor Reservation

    #region Doctor Reservation Detail 

    [Authorize]
    [HttpGet]
    public async Task<IActionResult> DocBooking(ulong userId, string? loggedDateTime, ulong? WorkAddressId)
    {
        #region Check Is Exist Any Waiting For Payment Reservation For This User

        var existInvoiceId = await _reservationService.IsExistAnyWaitingForPaymentReservationRequestByUserId(User.GetUserId());
        if (existInvoiceId != null && existInvoiceId.HasValue && existInvoiceId.Value != 0)
        {
            return RedirectToAction(nameof(ShowInvoiceBeforeRedirectToBankProtable), new { reservationDateTimeId = existInvoiceId, Reminder = true });
        }

        #endregion

        #region Fill Model

        var model = await _doctorService.FillDoctorReservationDetailForShowSiteSide(userId, loggedDateTime, WorkAddressId);
        if (model == null)
        {
            TempData[ErrorMessage] = "اطلاعات وارد شده صحیح نمی باشد.";
            return RedirectToAction("Index", "Diabet", new { area = "" });
        }

        #endregion

        #region List Of Reservation Days 

        if (loggedDateTime == null)
        {
            ViewBag.FutureDates = await _reservationService.ListOfFutureDaysOfDoctorReservation(userId);
        }

        #endregion

        return View(model);
    }

    [Authorize]
    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> DocBooking(ShowDoctorReservationDetailViewModel reservationDetail)
    {
        #region Check Is Exist Any Waiting For Payment Reservation For This User

        var existInvoiceId = await _reservationService.IsExistAnyWaitingForPaymentReservationRequestByUserId(User.GetUserId());
        if (existInvoiceId != null && existInvoiceId.HasValue && existInvoiceId.Value != 0)
        {
            return RedirectToAction(nameof(ShowInvoiceBeforeRedirectToBankProtable), new { reservationDateTimeId = existInvoiceId, Reminder = true });
        }

        #endregion

        #region Fill Model

        var model = await _doctorService.FillDoctorReservationDetailForShowSiteSide(reservationDetail.UserId, reservationDetail.LoggedDateTime, reservationDetail.WorkAddressId);
        if (model == null)
        {
            TempData[ErrorMessage] = "اطلاعات وارد شده صحیح نمی باشد.";
            return RedirectToAction("Index", "Diabet", new { area = "" });
        }

        #endregion

        return View(model);
    }

    #endregion

    #region Choose Type Of Reservation In Model

    [HttpGet("/Choose-Type-Of-Reservation")]
    public async Task<IActionResult> ChooseTypeOfReservationModal(ulong reservationDateTimeId, ulong doctorId)
    {
        #region Fill Model

        ChooseTypeOfReservationViewModel model = new ChooseTypeOfReservationViewModel()
        {
            DoctorId = doctorId,
            ReservationDateTimeId = reservationDateTimeId,
            DoctorSelectedReservationType = await _reservationService.GetDoctorReservationDateTimeDoctorSelectedReservationType(reservationDateTimeId),
            UserInfoForGetReservation = await _reservationService.GetPatientUserInformationsForGetReservationTimeFromDoctors(User.GetUserId())
        };

        #endregion

        return PartialView("_ChooseTypeOfReservation", model);
    }

    #endregion

    #region Choose Type Of Reservation

    [Authorize]
    public async Task<IActionResult> ChooseTypeOfReservation(ChooseTypeOfReservationViewModel model)
    {
        #region Check Is Exist Any Waiting For Payment Reservation For This User

        var existInvoiceId = await _reservationService.IsExistAnyWaitingForPaymentReservationRequestByUserId(User.GetUserId());
        if (existInvoiceId != null && existInvoiceId.HasValue && existInvoiceId.Value != 0)
        {
            return RedirectToAction(nameof(ShowInvoiceBeforeRedirectToBankProtable), new { reservationDateTimeId = existInvoiceId, Reminder = true });
        }

        #endregion

        #region Get Reservation Date Time 

        var reservationDateTime = await _reservationService.GetDoctorReservationDateTimeById(model.ReservationDateTimeId);
        if (reservationDateTime == null || reservationDateTime.DoctorReservationState != Domain.Enums.DoctorReservation.DoctorReservationState.NotReserved)
        {
            TempData[ErrorMessage] = "اطلاعات وارد شده صحیح نمی باشد.";
            return RedirectToAction("Index", "Home");
        }

        #endregion

        #region Change User Information By Incoming Data

DoctorFAM.Presentation/Views/FocalPoint/DocPage.cshtml
@model DoctorFAM.Domain.ViewModels.Site.Doctor.DoctorPageInReservationViewModel
@using DoctorFAM.Application.Extensions
@using DoctorFAM.Application.Convertors

@{
    ViewBag.Title = "پروفایل پزشک";
}

@section Scripts{
    <script src="~/Content/plugins/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js" data-cf-settings="c05b42694ff6ef93b74325a7-|49" defer=""></script>

}

<div class="content">
    <div class="container">

        <div class="card m-2 ">
            <div class="card-body">
                <div class="doctor-widget">
                    <div class="doc-info-left">
                        <div class="doctor-img">
                            <img src="/content/images/user/@((string.IsNullOrEmpty(Model.UserAvatar)) ? "DefaultAvatar.png" : $"thumb/{Model.UserAvatar}")" class="img-fluid" alt="User Image">
                        </div>
                        <div class="doc-info-cont">
                            <h4 class="doc-name">پزشک:دکتر @Model.Username</h4>
                            <p class="doc-speciality"> @((!string.IsNullOrEmpty(Model.Education)) ? Model.Education : null) - @((!string.IsNullOrEmpty(Model.Specialist)) ? Model.Specialist : null) </p>

                            <div class="rating">
                                <i class="fas fa-star filled"></i>
                                <i class="fas fa-star filled"></i>
                                <i class="fas fa-star filled"></i>
                                <i class="fas fa-star filled"></i>
                                <i class="fas fa-star"></i>
                                <span class="d-inline-block average-rating">(35)</span>
                            </div>
                            <hr />
                            <div class="clinic-details">
                                <p class="doc-location">
                                    @if (!string.IsNullOrEmpty(Model.CountryName) || !string.IsNullOrEmpty(Model.StateName) || !string.IsNullOrEmpty(Model.CityName))
                                    {
                                        <i class="fas fa-map-marker-alt"></i>
                                    }

                                    @((!string.IsNullOrEmpty(Model.CountryName)) ? Model.CountryName + "-" : null)
                                    @((!string.IsNullOrEmpty(Model.StateName)) ? Model.StateName + "-" : null)
                                    @((!string.IsNullOrEmpty(Model.CityName)) ? Model.CityName : null)

                                    <br />
                                    @if (!string.IsNullOrEmpty(Model.WorkAddress))
                                    {
                                        <i class="fas fa-map-marker-alt"></i>
                                    }
                                    @((string.IsNullOrEmpty(Model.WorkAddress)) ? null : Model.WorkAddress)
                                    <br />
                                    @*Box Of Work Address*@
                                    <partial name="_WorkAddressPartialINLine" model="@Model.WorkingAddressResume" />
                                    <br />
                                    @((!string.IsNullOrEmpty(Model.ClinicPhone)) ? Model.ClinicPhone : null)
                                    
                                    <br />
                                    @((!string.IsNullOrEmpty(Model.GeneralPhone)) ? Model.GeneralPhone : null)
                                   

                                </p>

                               
                                @*Box Of Gallery*@
                                <partial name="_GalleryPartial" model="@Model.GalleryResume" />

                            </div>
                            <div class="clinic-services">
                                <span>آنلاین</span>

                                @if (!string.IsNullOrEmpty(Model.CountryName) || !string.IsNullOrEmpty(Model.StateName) || !string.IsNullOrEmpty(Model.CityName))
                                {
                                    <span>حضوری</span>
                                }
                            </div>
                        </div>
                    </div>
                    <div class="doc-info-right">
                        @*<div class="clini-infos">
                        <ul>
                        <li><i class="far fa-thumbs-up"></i> 99%</li>
                        <li><i class="far fa-comment"></i> 35 فیدبک </li>

                        <li><i class="far fa-money-bill-alt"></i> حق ویزیت: سامانه </li>
                        </ul>
                        </div>*@
                        @*<div class="doctor-action">
                        <a href="javascript:void(0)" class="btnDoc btn-white fav-btn">
                        <i class="far fa-bookmark"></i>
                        </a>
                        <a href="chat.html" class="btnDoc btn-white msg-btn">
                        <i class="far fa-comment-alt"></i>
                        </a>
                        <a href="javascript:void(0)" class="btnDoc btn-white call-btn" data-bs-toggle="modal" data-bs-target="#voice_call">
                        <i class="fas fa-phone"></i>
                        </a>
                        <a href="javascript:void(0)" class="btnDoc btn-white call-btn" data-bs-toggle="modal" data-bs-target="#video_call">
                        <i class="fas fa-video"></i>
                        </a>
                        </div>*@
                       
                        <div class="clinic-booking mt-3">
                            <a class="apt-btn " asp-action="DocBooking" asp-controller="FocalPoint" asp-area="" asp-route-userId="@Model.UserId">رزرو نوبت</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        @if (Model.Resume != null && Model.Resume.ResumeState == DoctorFAM.Domain.Enums.ResumeState.ResumeState.Accepted)
        {
            <div class="card">
                <div class="card-body pt-0">

                    <nav class="user-tabs mb-4">
                        <ul class="nav nav-tabs nav-tabs-bottom nav-justified">
                            <li class="nav-item">
                                <a class="nav-link active" href="#doc_overview" data-bs-toggle="tab"> رزومه </a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="#doc_reviews" data-bs-toggle="tab">گواهینامه ها</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#doc_business_hours" data-bs-toggle="tab">کلیپها </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#doc_locations" data-bs-toggle="tab"> آدرس محل کار </a>
                            </li>
                        </ul>
                    </nav>

                    <div class="tab-content pt-0">

                        <div role="tabpanel" id="doc_overview" class="tab-pane fade show active">

                            @*Box Of ABout Me*@
                            <partial name="_LastestAboutMePartial" model="@Model.ResumeAboutMeSitePanelViewModel" />

                            <div class="row  text-center justify-content-center">

                                @*Box Of Education*@
                                <partial name="_EducationPartial" model="@Model.EducationResume" />

                                @*Box Of Work History*@
                                <partial name="_WorkHistoryPartial" model="@Model.WorkHistoryResume" />

                            </div>

                            <div class="row  text-center justify-content-center">

                                @*Box Of Honors*@
                                <partial name="_HonorsPartial" model="@Model.HonorResume" />

                            </div>

                            <div class="row text-center justify-content-center">

                                @*Box Of Services*@
                                <partial name="_ServicesPartial" model="@Model.ServiceResume" />

                            </div>

                        </div>

                        @*Box Of Work Address*@
                        <partial name="_WorkAddressPartial" model="@Model.WorkingAddressResume" />

                        @*Box Of Certificate*@
                        <partial name="_CertificatePartial" model="@Model.CertificateResume" />

                        <div role="tabpanel" id="doc_business_hours" class="tab-pane fade">
                            <div class="row">
                                <div class="col-md-6 offset-md-3">

                                    <div class="widget business-widget">
                                        <div class="widget-content">
                                            <div class="listing-hours">
                                            </div>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        }

    </div>
</div>

DoctorFAM.Presentation/Views/FocalPoint/DoctorReservationPayment.cshtml
@model DoctorFAM.Domain.ViewModels.Site.Reservation.ReservationFactorSiteSideViewModel
@using DoctorFAM.Application.Convertors
@using DoctorFAM.Application.Extensions
@using DoctorFAM.Application.StaticTools

@{
    ViewData["Title"] = "فاکتور شما";
}

@section Styles
    {
    <!--Basic Styles-->
    <link href="/admin/css/bootstrap.min.css" rel="stylesheet">
    <link id="bootstrap-rtl-link" href="/admin/css/bootstrap-rtl.min.css" rel="stylesheet">
    <link href="/admin/css/font-awesome.min.css" rel="stylesheet">
    <link href="/admin/css/weather-icons.min.css" rel="stylesheet">

    <!--Fonts-->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,600,700,300" rel="stylesheet" type="text/css">

    <!--Beyond styles-->
    <link id="beyond-link" href="/admin/css/beyond-rtl.min.css" rel="stylesheet">
    <link href="/admin/css/demo.min.css" rel="stylesheet">
    <link href="/admin/css/typicons.min.css" rel="stylesheet">
    <link href="/admin/css/animate.min.css" rel="stylesheet">
    <link id="skin-link" href="" rel="stylesheet" type="text/css">
}

@section Scripts
    {
    <partial name="_JqueryValidation" />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.9.3/html2pdf.bundle.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function ($) {

            $(document).on('click', '.btn_print', function (event) {
                event.preventDefault();

                //credit : https://ekoopmans.github.io/html2pdf.js

                var element = document.getElementById('container_content');

                //easy
                html2pdf().from(element).save();

            });
        });
    </script>
    }

<div class="row mt-5" id="container_content">
    <div class="col-lg-3 col-sm-12 col-xs-12">
    </div>
    <div class="col-lg-6 col-sm-12 col-xs-12">
        <div class="well invoice-container" style="background-color: cornflowerblue;">
            <div class="row">
                <div class="col-lg-4 col-sm-4 col-xs-4">
                </div>
                <div class="col-lg-5 col-sm-5 col-xs-5">
                    <h1>
                        <a href="">
                            <img src="/Content/images/Logo/doctorfamTes.png" alt="" style="width:200px; height:45px; margin-right:-17px">
                        </a>
                    </h1>
                    <div>
                        <span>کد رهگیری درخواست : </span>
                        <span>@Model.RefId</span>
                    </div>
                    <div class="horizontal-space"></div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 col-sm-12 col-xs-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h6>اطلاعات درخواست :</h6>
                        </div>
                        <div class="panel-body">
                            <ul>
                                <li>نام کاربری  : @Model.PatientUsername</li>
                                <li>موبایل : @Model.PatientMobile</li>

                              
                                @if (Model.DoctorAddress != null )
                                {
                                        <li>آدرس مطب : @Model.DoctorAddress.Address</li>
                                }
                            </ul>
                        </div>
                    </div>
                </div>
            </div> <!-- / end client details section -->
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th><h5 class="no-margin-bottom">عنوان </h5></th>
                        <th><h5 class="no-margin-bottom">توضیح </h5></th>
                    </tr>
                </thead>
                <tbody>

                    <tr>
                        <td>کدملی بیمار</td>
                        <td>@((!string.IsNullOrEmpty(Model.PatientNationalId)) ? Model.PatientNationalId : "وارد نشده")</td>
                    </tr>

                    <tr>
                        <td>نام و نام خانوادگی بیمار</td>
                        <td>@((!string.IsNullOrEmpty(Model.PatientUsername)) ? Model.PatientUsername : "وارد نشده")</td>
                    </tr>

                    <tr>
                        <td>نام پزشک</td>
                        <td>@((!string.IsNullOrEmpty(Model.DoctorUsername)) ? Model.DoctorUsername : "وارد نشده")</td>
                    </tr>

                    @if (Model.DoctorSpeciality != null && Model.DoctorSpeciality.Any())
                    {
                        <tr>

                            <td>تخصص پزشک</td>
                            <td>
                                @foreach (var skill in Model.DoctorSpeciality)
                                {
                                    <p>@skill.DoctorSkil</p>
                                }
                            </td>
                        </tr>
                    }

                    <tr>
                        <td>تاریخ نوبت</td>
                        <td>@Model.ReservationDate.ToStringShamsiDate()</td>
                    </tr>

                    <tr>
                        <td>ساعت مراجعه</td>
                        <td>@string.Concat(Model.ReservationDateTime.Reverse().Skip(3).Reverse())</td>
                    </tr>

                    <tr>
                        <td>مبلغ پرداختی</td>
                        <td>@Model.ReservationPrice.ToString("#,000") ریال</td>
                    </tr>

                    <tr>
                        <td>کد پیگیری</td>
                        <td>@Model.RefId</td>
                    </tr>

                    <tr>
                        <td class="text-center"><strong>عملیات  </strong></td>
                        <td class="text-center ">
                            <p class="btn btn-sccess btn_print">
                                چاپ و دانلود فاکتور
                            </p>
                        </td>
                    </tr>

                </tbody>
            </table>
        </div>
    </div>
</div>

DoctorFAM.Presentation/Views/FocalPoint/HomeVisitPayment.cshtml
@{
    ViewData["Title"] = "پرداخت مبلغ آزمایشگاه در منزل ";
}

<div class="page-content">

    <!--coming soon start-->

    <section class="fullscreen-banner p-0">
        <div class="container-fluid p-0 h-100">
            <div class="row h-100">
                <div class="col-lg-5 col-md-12 h-100 d-flex align-items-center text-center">
                    <div class="w-100">
                        <a class="logo" href="index.html">
                            <img id="logo-img" class="img-center" src="images/logo.png" alt="">
                        </a>

                        @if (ViewBag.IsSuccess == true)
                        {
                            <h1 class="mt-4 mb-2 font-w-7"> تراکنش موفقیت آمیز بوده است . </h1>
                        }
                        else
                        {
                            <h1 class="mt-4 mb-2 font-w-7"> تراکنش ناموفق بوده است .. </h1>
                        }

                    </div>
                </div>
                <div class="col-lg-7 col-md-12 h-100 dark-bg p-5 d-flex align-items-center">
                    <div class="coming-soon w-100">
                        <ul class="countdown list-inline d-flex justify-content-between" data-countdown="2022/07/15"></ul>
                        <div>
                            <h4 class="title z-index-1 mb-4"> برای اطلاع رسانی مشترک شوید! </h4>
                            <div class="subscribe-form xs-w-100 w-50">
                                <form id="mc-form" class="group">
                                    <input type="email" value="" name="EMAIL" class="email" id="mc-email" placeholder="آدرس ایمیل را وارد کنید" required="">
                                    <input class="btn-Accept" type="submit" name="subscribe" value="اشتراک">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!--coming soon end-->

</div>

DoctorFAM.Presentation/Views/FocalPoint/_CertificatePartialOld.cshtml
@model List<DoctorFAM.Domain.ViewModels.Site.Doctor.Resume.Certificate.CertificateResumeInSitePanelViewModel>
@using DoctorFAM.Application.Convertors
@using DoctorFAM.Application.Extensions
@using DoctorFAM.Application.StaticTools

@if (Model != null && Model.Any())
{

    <div class="widget">
        <div class="banner medium-opacity bluesh">
            <div style="background-image: url(images/resources/baner-widgetbg.jpg)" class="bg-image"></div>
            <div class="baner-top">
                <span><img src="images/book-icon.png" alt="">گواهینامه ها</span>

            </div>
            <div class="banermeta">


                @*Box Of Certificate*@
                @foreach (var item in Model)
                {

                    <div class="row ">

                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                           

                                @if (!string.IsNullOrEmpty(item.CertificateTitle))
                                {
                                    <p class="text-white">
                                        <a href="#"><u>@item.CertificateTitle</u></a>
                                    </p>
                                }
                                @if (!string.IsNullOrEmpty(item.ExporterRefrence))
                                {
                                    <p class="text-white">@item.ExporterRefrence</p>
                                }


                           
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                            
                                @if (!string.IsNullOrEmpty(item.ImageName))
                                {
                                    <a href="@PathTools.CertificatePathThumb@item.ImageName" target="_blank"> <img style="border-radius: 8px;height: 90px;" src="@PathTools.CertificatePathThumb@item.ImageName" /></a>
                                }

                            
                        </div>
                    </div>
                    <hr />


                }


            </div>
        </div>
    </div>



}

DoctorFAM.Presentation/Views/FocalPoint/_GalleryPartialOld.cshtml
@model List<DoctorFAM.Domain.ViewModels.Site.Doctor.Resume.Gallery.GalleryResumeInSitePanelViewModel>
@using DoctorFAM.Application.Convertors
@using DoctorFAM.Application.Extensions
@using DoctorFAM.Application.StaticTools

@if (Model != null && Model.Any())
{
    <ul class="photos">
        @foreach (var item in Model)
        {
            <li>


                <a class="strip" href="@PathTools.ResumeGalleryPath@item.ImageName" data-strip-group="mygroup" data-strip-group-options="loop: false">
                    <img src="@PathTools.ResumeGalleryPath@item.ImageName" alt="">
                </a>
            </li>
        }
    </ul>
}

DoctorFAM.Presentation/Views/FocalPoint/_ServicesPartialOld.cshtml
@model List<DoctorFAM.Domain.ViewModels.Site.Doctor.Resume.Service.ServiceResumeInSitePanelViewModel>
@using DoctorFAM.Application.Convertors
@using DoctorFAM.Application.Extensions




@if (Model != null && Model.Any())
{
    <div class="widget">
        <div class="banner medium-opacity bluesh">
            <div style="background-image: url(images/resources/baner-widgetbg.jpg)" class="bg-image"></div>
            <div class="baner-top">
                <span><img src="images/book-icon.png" alt="">خدمات</span>

            </div>
            <div class="banermeta">
                <div class="row ">
                   
                    @foreach (var item in Model)
                    {
                        <span style="padding:5px;">* @item.ServiceTitle</span>
                    }
                </div>
            </div>
        </div>
    </div>

   

}